# Use Python 3.11 slim base image
FROM python:3.11-slim

# Set working directory
WORKDIR /api

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all your app files
COPY . .

# Set default command
CMD ["python", "api.py"]
